version: "3.7"

services:
  database:
    image: postgres
    container_name: rentx_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  api:
    build: .
    container_name: rentx_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - "database"
    depends_on:
      - database


volumes:
  pgdata:
    driver: local
